# Generated by Django 2.0.4 on 2018-05-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleType',
            field=models.ForeignKey(null=True, on_delete=True, to='blog.ArticleType'),
        ),
    ]
